
interface _GlobalComponents {
      'AuthSignUpLogo': typeof import("../components/Auth/SignUp/Logo.vue")['default']
    'AuthSignUpForm': typeof import("../components/Auth/SignUp/form.vue")['default']
    'AuthSignUpImage': typeof import("../components/Auth/SignUp/image.vue")['default']
    'FooterMenu': typeof import("../components/Footer/Menu.vue")['default']
    'FooterSocial': typeof import("../components/Footer/Social.vue")['default']
    'HeaderHeroBackground': typeof import("../components/Header/Hero/Background.vue")['default']
    'HeaderHeroButtons': typeof import("../components/Header/Hero/Buttons.vue")['default']
    'HeaderHeroSubTitle': typeof import("../components/Header/Hero/SubTitle.vue")['default']
    'HeaderHeroTitle': typeof import("../components/Header/Hero/Title.vue")['default']
    'HeaderHeroImage': typeof import("../components/Header/Hero/image.vue")['default']
    'MainAboutButtonMore': typeof import("../components/Main/About/ButtonMore.vue")['default']
    'MainAboutDescription': typeof import("../components/Main/About/Description.vue")['default']
    'MainAboutImage': typeof import("../components/Main/About/Image.vue")['default']
    'MainAboutSubTitle': typeof import("../components/Main/About/SubTitle.vue")['default']
    'MainAboutTitle': typeof import("../components/Main/About/Title.vue")['default']
    'MainPetDanimApiHeaderReadMore': typeof import("../components/Main/PetDanimApi/Header/ReadMore.vue")['default']
    'MainPetDanimApiHeaderTitle': typeof import("../components/Main/PetDanimApi/Header/Title.vue")['default']
    'MainPetDanimApiPostsAuther': typeof import("../components/Main/PetDanimApi/Posts/Auther.vue")['default']
    'MainPetDanimApiPostsDate': typeof import("../components/Main/PetDanimApi/Posts/Date.vue")['default']
    'MainPetDanimApiPostsDescription': typeof import("../components/Main/PetDanimApi/Posts/Description.vue")['default']
    'MainPetDanimApiPostsReadMore': typeof import("../components/Main/PetDanimApi/Posts/ReadMore.vue")['default']
    'MainPetDanimApiPostsShareSocial': typeof import("../components/Main/PetDanimApi/Posts/Share/social.vue")['default']
    'MainPetDanimApiPostsTitle': typeof import("../components/Main/PetDanimApi/Posts/Title.vue")['default']
    'MainPetDanimApiPostsView': typeof import("../components/Main/PetDanimApi/Posts/View.vue")['default']
    'MainServicesHeaderSubTitle': typeof import("../components/Main/Services/Header/SubTitle.vue")['default']
    'MainServicesHeaderTitle': typeof import("../components/Main/Services/Header/Title.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'VitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'PwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'PwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'PwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'PwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'PwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAuthSignUpLogo': typeof import("../components/Auth/SignUp/Logo.vue")['default']
    'LazyAuthSignUpForm': typeof import("../components/Auth/SignUp/form.vue")['default']
    'LazyAuthSignUpImage': typeof import("../components/Auth/SignUp/image.vue")['default']
    'LazyFooterMenu': typeof import("../components/Footer/Menu.vue")['default']
    'LazyFooterSocial': typeof import("../components/Footer/Social.vue")['default']
    'LazyHeaderHeroBackground': typeof import("../components/Header/Hero/Background.vue")['default']
    'LazyHeaderHeroButtons': typeof import("../components/Header/Hero/Buttons.vue")['default']
    'LazyHeaderHeroSubTitle': typeof import("../components/Header/Hero/SubTitle.vue")['default']
    'LazyHeaderHeroTitle': typeof import("../components/Header/Hero/Title.vue")['default']
    'LazyHeaderHeroImage': typeof import("../components/Header/Hero/image.vue")['default']
    'LazyMainAboutButtonMore': typeof import("../components/Main/About/ButtonMore.vue")['default']
    'LazyMainAboutDescription': typeof import("../components/Main/About/Description.vue")['default']
    'LazyMainAboutImage': typeof import("../components/Main/About/Image.vue")['default']
    'LazyMainAboutSubTitle': typeof import("../components/Main/About/SubTitle.vue")['default']
    'LazyMainAboutTitle': typeof import("../components/Main/About/Title.vue")['default']
    'LazyMainPetDanimApiHeaderReadMore': typeof import("../components/Main/PetDanimApi/Header/ReadMore.vue")['default']
    'LazyMainPetDanimApiHeaderTitle': typeof import("../components/Main/PetDanimApi/Header/Title.vue")['default']
    'LazyMainPetDanimApiPostsAuther': typeof import("../components/Main/PetDanimApi/Posts/Auther.vue")['default']
    'LazyMainPetDanimApiPostsDate': typeof import("../components/Main/PetDanimApi/Posts/Date.vue")['default']
    'LazyMainPetDanimApiPostsDescription': typeof import("../components/Main/PetDanimApi/Posts/Description.vue")['default']
    'LazyMainPetDanimApiPostsReadMore': typeof import("../components/Main/PetDanimApi/Posts/ReadMore.vue")['default']
    'LazyMainPetDanimApiPostsShareSocial': typeof import("../components/Main/PetDanimApi/Posts/Share/social.vue")['default']
    'LazyMainPetDanimApiPostsTitle': typeof import("../components/Main/PetDanimApi/Posts/Title.vue")['default']
    'LazyMainPetDanimApiPostsView': typeof import("../components/Main/PetDanimApi/Posts/View.vue")['default']
    'LazyMainServicesHeaderSubTitle': typeof import("../components/Main/Services/Header/SubTitle.vue")['default']
    'LazyMainServicesHeaderTitle': typeof import("../components/Main/Services/Header/Title.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyVitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'LazyPwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'LazyPwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'LazyPwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'LazyPwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'LazyPwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AuthSignUpLogo: typeof import("../components/Auth/SignUp/Logo.vue")['default']
export const AuthSignUpForm: typeof import("../components/Auth/SignUp/form.vue")['default']
export const AuthSignUpImage: typeof import("../components/Auth/SignUp/image.vue")['default']
export const FooterMenu: typeof import("../components/Footer/Menu.vue")['default']
export const FooterSocial: typeof import("../components/Footer/Social.vue")['default']
export const HeaderHeroBackground: typeof import("../components/Header/Hero/Background.vue")['default']
export const HeaderHeroButtons: typeof import("../components/Header/Hero/Buttons.vue")['default']
export const HeaderHeroSubTitle: typeof import("../components/Header/Hero/SubTitle.vue")['default']
export const HeaderHeroTitle: typeof import("../components/Header/Hero/Title.vue")['default']
export const HeaderHeroImage: typeof import("../components/Header/Hero/image.vue")['default']
export const MainAboutButtonMore: typeof import("../components/Main/About/ButtonMore.vue")['default']
export const MainAboutDescription: typeof import("../components/Main/About/Description.vue")['default']
export const MainAboutImage: typeof import("../components/Main/About/Image.vue")['default']
export const MainAboutSubTitle: typeof import("../components/Main/About/SubTitle.vue")['default']
export const MainAboutTitle: typeof import("../components/Main/About/Title.vue")['default']
export const MainPetDanimApiHeaderReadMore: typeof import("../components/Main/PetDanimApi/Header/ReadMore.vue")['default']
export const MainPetDanimApiHeaderTitle: typeof import("../components/Main/PetDanimApi/Header/Title.vue")['default']
export const MainPetDanimApiPostsAuther: typeof import("../components/Main/PetDanimApi/Posts/Auther.vue")['default']
export const MainPetDanimApiPostsDate: typeof import("../components/Main/PetDanimApi/Posts/Date.vue")['default']
export const MainPetDanimApiPostsDescription: typeof import("../components/Main/PetDanimApi/Posts/Description.vue")['default']
export const MainPetDanimApiPostsReadMore: typeof import("../components/Main/PetDanimApi/Posts/ReadMore.vue")['default']
export const MainPetDanimApiPostsShareSocial: typeof import("../components/Main/PetDanimApi/Posts/Share/social.vue")['default']
export const MainPetDanimApiPostsTitle: typeof import("../components/Main/PetDanimApi/Posts/Title.vue")['default']
export const MainPetDanimApiPostsView: typeof import("../components/Main/PetDanimApi/Posts/View.vue")['default']
export const MainServicesHeaderSubTitle: typeof import("../components/Main/Services/Header/SubTitle.vue")['default']
export const MainServicesHeaderTitle: typeof import("../components/Main/Services/Header/Title.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAuthSignUpLogo: typeof import("../components/Auth/SignUp/Logo.vue")['default']
export const LazyAuthSignUpForm: typeof import("../components/Auth/SignUp/form.vue")['default']
export const LazyAuthSignUpImage: typeof import("../components/Auth/SignUp/image.vue")['default']
export const LazyFooterMenu: typeof import("../components/Footer/Menu.vue")['default']
export const LazyFooterSocial: typeof import("../components/Footer/Social.vue")['default']
export const LazyHeaderHeroBackground: typeof import("../components/Header/Hero/Background.vue")['default']
export const LazyHeaderHeroButtons: typeof import("../components/Header/Hero/Buttons.vue")['default']
export const LazyHeaderHeroSubTitle: typeof import("../components/Header/Hero/SubTitle.vue")['default']
export const LazyHeaderHeroTitle: typeof import("../components/Header/Hero/Title.vue")['default']
export const LazyHeaderHeroImage: typeof import("../components/Header/Hero/image.vue")['default']
export const LazyMainAboutButtonMore: typeof import("../components/Main/About/ButtonMore.vue")['default']
export const LazyMainAboutDescription: typeof import("../components/Main/About/Description.vue")['default']
export const LazyMainAboutImage: typeof import("../components/Main/About/Image.vue")['default']
export const LazyMainAboutSubTitle: typeof import("../components/Main/About/SubTitle.vue")['default']
export const LazyMainAboutTitle: typeof import("../components/Main/About/Title.vue")['default']
export const LazyMainPetDanimApiHeaderReadMore: typeof import("../components/Main/PetDanimApi/Header/ReadMore.vue")['default']
export const LazyMainPetDanimApiHeaderTitle: typeof import("../components/Main/PetDanimApi/Header/Title.vue")['default']
export const LazyMainPetDanimApiPostsAuther: typeof import("../components/Main/PetDanimApi/Posts/Auther.vue")['default']
export const LazyMainPetDanimApiPostsDate: typeof import("../components/Main/PetDanimApi/Posts/Date.vue")['default']
export const LazyMainPetDanimApiPostsDescription: typeof import("../components/Main/PetDanimApi/Posts/Description.vue")['default']
export const LazyMainPetDanimApiPostsReadMore: typeof import("../components/Main/PetDanimApi/Posts/ReadMore.vue")['default']
export const LazyMainPetDanimApiPostsShareSocial: typeof import("../components/Main/PetDanimApi/Posts/Share/social.vue")['default']
export const LazyMainPetDanimApiPostsTitle: typeof import("../components/Main/PetDanimApi/Posts/Title.vue")['default']
export const LazyMainPetDanimApiPostsView: typeof import("../components/Main/PetDanimApi/Posts/View.vue")['default']
export const LazyMainServicesHeaderSubTitle: typeof import("../components/Main/Services/Header/SubTitle.vue")['default']
export const LazyMainServicesHeaderTitle: typeof import("../components/Main/Services/Header/Title.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyVitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const LazyPwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const LazyPwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const LazyPwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const LazyPwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const LazyPwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
