
interface _GlobalComponents {
      'About': typeof import("../components/About/About.vue")['default']
    'AboutButtonMore': typeof import("../components/About/ButtonMore.vue")['default']
    'AboutDescription': typeof import("../components/About/Description.vue")['default']
    'AboutImage': typeof import("../components/About/Image.vue")['default']
    'AboutSubTitle': typeof import("../components/About/SubTitle.vue")['default']
    'AboutTitle': typeof import("../components/About/Title.vue")['default']
    'AuthFormSignUp': typeof import("../components/Auth/Form/FormSignUp.vue")['default']
    'AuthFormVerifyCode': typeof import("../components/Auth/Form/FormVerifyCode.vue")['default']
    'AuthHeaderForm': typeof import("../components/Auth/HeaderForm/HeaderForm.vue")['default']
    'AuthHeaderFormVerify': typeof import("../components/Auth/HeaderForm/HeaderFormVerify.vue")['default']
    'AuthImage': typeof import("../components/Auth/Image.vue")['default']
    'AuthLogo': typeof import("../components/Auth/Logo.vue")['default']
    'AuthSignUp': typeof import("../components/Auth/SignUp.vue")['default']
    'AuthVerify': typeof import("../components/Auth/Verify.vue")['default']
    'Footer': typeof import("../components/Footer/Footer.vue")['default']
    'FooterMobile': typeof import("../components/Footer/FooterMobile.vue")['default']
    'FooterMenu': typeof import("../components/Footer/Menu.vue")['default']
    'FooterSocial': typeof import("../components/Footer/Social.vue")['default']
    'HeaderDesktop': typeof import("../components/Header/HeaderDesktop.vue")['default']
    'HeaderMobile': typeof import("../components/Header/HeaderMobile.vue")['default']
    'HeaderLogo': typeof import("../components/Header/Logo/logo.vue")['default']
    'HeaderMenu': typeof import("../components/Header/Menu/Menu.vue")['default']
    'HeroButtons': typeof import("../components/Hero/Buttons.vue")['default']
    'Hero': typeof import("../components/Hero/Hero.vue")['default']
    'HeroSubTitle': typeof import("../components/Hero/SubTitle.vue")['default']
    'HeroTitle': typeof import("../components/Hero/Title.vue")['default']
    'HeroImage': typeof import("../components/Hero/image.vue")['default']
    'IconsAboutIcon': typeof import("../components/Icons/AboutIcon.vue")['default']
    'IconsHeart': typeof import("../components/Icons/Heart.vue")['default']
    'IconsSupportIcon': typeof import("../components/Icons/SupportIcon.vue")['default']
    'IconsTerms': typeof import("../components/Icons/Terms.vue")['default']
    'PagesHeaderTeam': typeof import("../components/Pages/Header/HeaderTeam.vue")['default']
    'PagesHeaderTerms': typeof import("../components/Pages/Header/HeaderTerms.vue")['default']
    'PagesHeader': typeof import("../components/Pages/Header/header.vue")['default']
    'PagesHeaderAbout': typeof import("../components/Pages/Header/headerAbout.vue")['default']
    'PagesAbout': typeof import("../components/Pages/about.vue")['default']
    'PagesContact': typeof import("../components/Pages/contact.vue")['default']
    'PagesTeam': typeof import("../components/Pages/team.vue")['default']
    'PagesTerms': typeof import("../components/Pages/terms.vue")['default']
    'PetDanimApiHeaderReadMore': typeof import("../components/PetDanimApi/Header/ReadMore.vue")['default']
    'PetDanimApiHeaderTitle': typeof import("../components/PetDanimApi/Header/Title.vue")['default']
    'PetDanimApiNews': typeof import("../components/PetDanimApi/News.vue")['default']
    'PetDanimApiPostsAuther': typeof import("../components/PetDanimApi/Posts/Auther.vue")['default']
    'PetDanimApiPostsDate': typeof import("../components/PetDanimApi/Posts/Date.vue")['default']
    'PetDanimApiPostsDescription': typeof import("../components/PetDanimApi/Posts/Description.vue")['default']
    'PetDanimApiPostsImage': typeof import("../components/PetDanimApi/Posts/Image.vue")['default']
    'PetDanimApiPostsReadMore': typeof import("../components/PetDanimApi/Posts/ReadMore.vue")['default']
    'PetDanimApiPostsShareSocial': typeof import("../components/PetDanimApi/Posts/Share/social.vue")['default']
    'PetDanimApiPostsSliderItem': typeof import("../components/PetDanimApi/Posts/SliderItem.vue")['default']
    'PetDanimApiPostsTitle': typeof import("../components/PetDanimApi/Posts/Title.vue")['default']
    'PetDanimApiPostsView': typeof import("../components/PetDanimApi/Posts/View.vue")['default']
    'QuestionsHeader': typeof import("../components/Questions/Header/header.vue")['default']
    'QuestionsQuestion': typeof import("../components/Questions/question.vue")['default']
    'ServicesPetMarketTabList': typeof import("../components/Services/PetMarket/TabList.vue")['default']
    'ServicesPetMarketLanding': typeof import("../components/Services/PetMarket/landing.vue")['default']
    'ServicesPetMarketQuestionFaqs': typeof import("../components/Services/PetMarket/question/faqs.vue")['default']
    'Services': typeof import("../components/Services/Services.vue")['default']
    'Slider': typeof import("../components/Slider/slider.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'VitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'PwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'PwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'PwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'PwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'PwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'Splide': typeof import("@splidejs/vue-splide")['Splide']
    'SplideSlide': typeof import("@splidejs/vue-splide")['SplideSlide']
    'SplideTrack': typeof import("@splidejs/vue-splide")['SplideTrack']
    'LCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
      'LazyAbout': typeof import("../components/About/About.vue")['default']
    'LazyAboutButtonMore': typeof import("../components/About/ButtonMore.vue")['default']
    'LazyAboutDescription': typeof import("../components/About/Description.vue")['default']
    'LazyAboutImage': typeof import("../components/About/Image.vue")['default']
    'LazyAboutSubTitle': typeof import("../components/About/SubTitle.vue")['default']
    'LazyAboutTitle': typeof import("../components/About/Title.vue")['default']
    'LazyAuthFormSignUp': typeof import("../components/Auth/Form/FormSignUp.vue")['default']
    'LazyAuthFormVerifyCode': typeof import("../components/Auth/Form/FormVerifyCode.vue")['default']
    'LazyAuthHeaderForm': typeof import("../components/Auth/HeaderForm/HeaderForm.vue")['default']
    'LazyAuthHeaderFormVerify': typeof import("../components/Auth/HeaderForm/HeaderFormVerify.vue")['default']
    'LazyAuthImage': typeof import("../components/Auth/Image.vue")['default']
    'LazyAuthLogo': typeof import("../components/Auth/Logo.vue")['default']
    'LazyAuthSignUp': typeof import("../components/Auth/SignUp.vue")['default']
    'LazyAuthVerify': typeof import("../components/Auth/Verify.vue")['default']
    'LazyFooter': typeof import("../components/Footer/Footer.vue")['default']
    'LazyFooterMobile': typeof import("../components/Footer/FooterMobile.vue")['default']
    'LazyFooterMenu': typeof import("../components/Footer/Menu.vue")['default']
    'LazyFooterSocial': typeof import("../components/Footer/Social.vue")['default']
    'LazyHeaderDesktop': typeof import("../components/Header/HeaderDesktop.vue")['default']
    'LazyHeaderMobile': typeof import("../components/Header/HeaderMobile.vue")['default']
    'LazyHeaderLogo': typeof import("../components/Header/Logo/logo.vue")['default']
    'LazyHeaderMenu': typeof import("../components/Header/Menu/Menu.vue")['default']
    'LazyHeroButtons': typeof import("../components/Hero/Buttons.vue")['default']
    'LazyHero': typeof import("../components/Hero/Hero.vue")['default']
    'LazyHeroSubTitle': typeof import("../components/Hero/SubTitle.vue")['default']
    'LazyHeroTitle': typeof import("../components/Hero/Title.vue")['default']
    'LazyHeroImage': typeof import("../components/Hero/image.vue")['default']
    'LazyIconsAboutIcon': typeof import("../components/Icons/AboutIcon.vue")['default']
    'LazyIconsHeart': typeof import("../components/Icons/Heart.vue")['default']
    'LazyIconsSupportIcon': typeof import("../components/Icons/SupportIcon.vue")['default']
    'LazyIconsTerms': typeof import("../components/Icons/Terms.vue")['default']
    'LazyPagesHeaderTeam': typeof import("../components/Pages/Header/HeaderTeam.vue")['default']
    'LazyPagesHeaderTerms': typeof import("../components/Pages/Header/HeaderTerms.vue")['default']
    'LazyPagesHeader': typeof import("../components/Pages/Header/header.vue")['default']
    'LazyPagesHeaderAbout': typeof import("../components/Pages/Header/headerAbout.vue")['default']
    'LazyPagesAbout': typeof import("../components/Pages/about.vue")['default']
    'LazyPagesContact': typeof import("../components/Pages/contact.vue")['default']
    'LazyPagesTeam': typeof import("../components/Pages/team.vue")['default']
    'LazyPagesTerms': typeof import("../components/Pages/terms.vue")['default']
    'LazyPetDanimApiHeaderReadMore': typeof import("../components/PetDanimApi/Header/ReadMore.vue")['default']
    'LazyPetDanimApiHeaderTitle': typeof import("../components/PetDanimApi/Header/Title.vue")['default']
    'LazyPetDanimApiNews': typeof import("../components/PetDanimApi/News.vue")['default']
    'LazyPetDanimApiPostsAuther': typeof import("../components/PetDanimApi/Posts/Auther.vue")['default']
    'LazyPetDanimApiPostsDate': typeof import("../components/PetDanimApi/Posts/Date.vue")['default']
    'LazyPetDanimApiPostsDescription': typeof import("../components/PetDanimApi/Posts/Description.vue")['default']
    'LazyPetDanimApiPostsImage': typeof import("../components/PetDanimApi/Posts/Image.vue")['default']
    'LazyPetDanimApiPostsReadMore': typeof import("../components/PetDanimApi/Posts/ReadMore.vue")['default']
    'LazyPetDanimApiPostsShareSocial': typeof import("../components/PetDanimApi/Posts/Share/social.vue")['default']
    'LazyPetDanimApiPostsSliderItem': typeof import("../components/PetDanimApi/Posts/SliderItem.vue")['default']
    'LazyPetDanimApiPostsTitle': typeof import("../components/PetDanimApi/Posts/Title.vue")['default']
    'LazyPetDanimApiPostsView': typeof import("../components/PetDanimApi/Posts/View.vue")['default']
    'LazyQuestionsHeader': typeof import("../components/Questions/Header/header.vue")['default']
    'LazyQuestionsQuestion': typeof import("../components/Questions/question.vue")['default']
    'LazyServicesPetMarketTabList': typeof import("../components/Services/PetMarket/TabList.vue")['default']
    'LazyServicesPetMarketLanding': typeof import("../components/Services/PetMarket/landing.vue")['default']
    'LazyServicesPetMarketQuestionFaqs': typeof import("../components/Services/PetMarket/question/faqs.vue")['default']
    'LazyServices': typeof import("../components/Services/Services.vue")['default']
    'LazySlider': typeof import("../components/Slider/slider.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyVitePwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaManifest': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'LazyNuxtPwaAssets': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'LazyPwaAppleImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'LazyPwaAppleSplashScreenImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'LazyPwaFaviconImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'LazyPwaMaskableImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'LazyPwaTransparentImage': typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'LazySplide': typeof import("@splidejs/vue-splide")['Splide']
    'LazySplideSlide': typeof import("@splidejs/vue-splide")['SplideSlide']
    'LazySplideTrack': typeof import("@splidejs/vue-splide")['SplideTrack']
    'LazyLCircle': typeof import("@vue-leaflet/vue-leaflet")['LCircle']
    'LazyLCircleMarker': typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
    'LazyLControl': typeof import("@vue-leaflet/vue-leaflet")['LControl']
    'LazyLControlAttribution': typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
    'LazyLControlLayers': typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
    'LazyLControlScale': typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
    'LazyLControlZoom': typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
    'LazyLFeatureGroup': typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
    'LazyLGeoJson': typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
    'LazyLIcon': typeof import("@vue-leaflet/vue-leaflet")['LIcon']
    'LazyLImageOverlay': typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
    'LazyLLayerGroup': typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
    'LazyLMap': typeof import("@vue-leaflet/vue-leaflet")['LMap']
    'LazyLMarker': typeof import("@vue-leaflet/vue-leaflet")['LMarker']
    'LazyLPolygon': typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
    'LazyLPolyline': typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
    'LazyLPopup': typeof import("@vue-leaflet/vue-leaflet")['LPopup']
    'LazyLRectangle': typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
    'LazyLTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
    'LazyLTooltip': typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
    'LazyLWmsTileLayer': typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const About: typeof import("../components/About/About.vue")['default']
export const AboutButtonMore: typeof import("../components/About/ButtonMore.vue")['default']
export const AboutDescription: typeof import("../components/About/Description.vue")['default']
export const AboutImage: typeof import("../components/About/Image.vue")['default']
export const AboutSubTitle: typeof import("../components/About/SubTitle.vue")['default']
export const AboutTitle: typeof import("../components/About/Title.vue")['default']
export const AuthFormSignUp: typeof import("../components/Auth/Form/FormSignUp.vue")['default']
export const AuthFormVerifyCode: typeof import("../components/Auth/Form/FormVerifyCode.vue")['default']
export const AuthHeaderForm: typeof import("../components/Auth/HeaderForm/HeaderForm.vue")['default']
export const AuthHeaderFormVerify: typeof import("../components/Auth/HeaderForm/HeaderFormVerify.vue")['default']
export const AuthImage: typeof import("../components/Auth/Image.vue")['default']
export const AuthLogo: typeof import("../components/Auth/Logo.vue")['default']
export const AuthSignUp: typeof import("../components/Auth/SignUp.vue")['default']
export const AuthVerify: typeof import("../components/Auth/Verify.vue")['default']
export const Footer: typeof import("../components/Footer/Footer.vue")['default']
export const FooterMobile: typeof import("../components/Footer/FooterMobile.vue")['default']
export const FooterMenu: typeof import("../components/Footer/Menu.vue")['default']
export const FooterSocial: typeof import("../components/Footer/Social.vue")['default']
export const HeaderDesktop: typeof import("../components/Header/HeaderDesktop.vue")['default']
export const HeaderMobile: typeof import("../components/Header/HeaderMobile.vue")['default']
export const HeaderLogo: typeof import("../components/Header/Logo/logo.vue")['default']
export const HeaderMenu: typeof import("../components/Header/Menu/Menu.vue")['default']
export const HeroButtons: typeof import("../components/Hero/Buttons.vue")['default']
export const Hero: typeof import("../components/Hero/Hero.vue")['default']
export const HeroSubTitle: typeof import("../components/Hero/SubTitle.vue")['default']
export const HeroTitle: typeof import("../components/Hero/Title.vue")['default']
export const HeroImage: typeof import("../components/Hero/image.vue")['default']
export const IconsAboutIcon: typeof import("../components/Icons/AboutIcon.vue")['default']
export const IconsHeart: typeof import("../components/Icons/Heart.vue")['default']
export const IconsSupportIcon: typeof import("../components/Icons/SupportIcon.vue")['default']
export const IconsTerms: typeof import("../components/Icons/Terms.vue")['default']
export const PagesHeaderTeam: typeof import("../components/Pages/Header/HeaderTeam.vue")['default']
export const PagesHeaderTerms: typeof import("../components/Pages/Header/HeaderTerms.vue")['default']
export const PagesHeader: typeof import("../components/Pages/Header/header.vue")['default']
export const PagesHeaderAbout: typeof import("../components/Pages/Header/headerAbout.vue")['default']
export const PagesAbout: typeof import("../components/Pages/about.vue")['default']
export const PagesContact: typeof import("../components/Pages/contact.vue")['default']
export const PagesTeam: typeof import("../components/Pages/team.vue")['default']
export const PagesTerms: typeof import("../components/Pages/terms.vue")['default']
export const PetDanimApiHeaderReadMore: typeof import("../components/PetDanimApi/Header/ReadMore.vue")['default']
export const PetDanimApiHeaderTitle: typeof import("../components/PetDanimApi/Header/Title.vue")['default']
export const PetDanimApiNews: typeof import("../components/PetDanimApi/News.vue")['default']
export const PetDanimApiPostsAuther: typeof import("../components/PetDanimApi/Posts/Auther.vue")['default']
export const PetDanimApiPostsDate: typeof import("../components/PetDanimApi/Posts/Date.vue")['default']
export const PetDanimApiPostsDescription: typeof import("../components/PetDanimApi/Posts/Description.vue")['default']
export const PetDanimApiPostsImage: typeof import("../components/PetDanimApi/Posts/Image.vue")['default']
export const PetDanimApiPostsReadMore: typeof import("../components/PetDanimApi/Posts/ReadMore.vue")['default']
export const PetDanimApiPostsShareSocial: typeof import("../components/PetDanimApi/Posts/Share/social.vue")['default']
export const PetDanimApiPostsSliderItem: typeof import("../components/PetDanimApi/Posts/SliderItem.vue")['default']
export const PetDanimApiPostsTitle: typeof import("../components/PetDanimApi/Posts/Title.vue")['default']
export const PetDanimApiPostsView: typeof import("../components/PetDanimApi/Posts/View.vue")['default']
export const QuestionsHeader: typeof import("../components/Questions/Header/header.vue")['default']
export const QuestionsQuestion: typeof import("../components/Questions/question.vue")['default']
export const ServicesPetMarketTabList: typeof import("../components/Services/PetMarket/TabList.vue")['default']
export const ServicesPetMarketLanding: typeof import("../components/Services/PetMarket/landing.vue")['default']
export const ServicesPetMarketQuestionFaqs: typeof import("../components/Services/PetMarket/question/faqs.vue")['default']
export const Services: typeof import("../components/Services/Services.vue")['default']
export const Slider: typeof import("../components/Slider/slider.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const Splide: typeof import("@splidejs/vue-splide")['Splide']
export const SplideSlide: typeof import("@splidejs/vue-splide")['SplideSlide']
export const SplideTrack: typeof import("@splidejs/vue-splide")['SplideTrack']
export const LCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyAbout: typeof import("../components/About/About.vue")['default']
export const LazyAboutButtonMore: typeof import("../components/About/ButtonMore.vue")['default']
export const LazyAboutDescription: typeof import("../components/About/Description.vue")['default']
export const LazyAboutImage: typeof import("../components/About/Image.vue")['default']
export const LazyAboutSubTitle: typeof import("../components/About/SubTitle.vue")['default']
export const LazyAboutTitle: typeof import("../components/About/Title.vue")['default']
export const LazyAuthFormSignUp: typeof import("../components/Auth/Form/FormSignUp.vue")['default']
export const LazyAuthFormVerifyCode: typeof import("../components/Auth/Form/FormVerifyCode.vue")['default']
export const LazyAuthHeaderForm: typeof import("../components/Auth/HeaderForm/HeaderForm.vue")['default']
export const LazyAuthHeaderFormVerify: typeof import("../components/Auth/HeaderForm/HeaderFormVerify.vue")['default']
export const LazyAuthImage: typeof import("../components/Auth/Image.vue")['default']
export const LazyAuthLogo: typeof import("../components/Auth/Logo.vue")['default']
export const LazyAuthSignUp: typeof import("../components/Auth/SignUp.vue")['default']
export const LazyAuthVerify: typeof import("../components/Auth/Verify.vue")['default']
export const LazyFooter: typeof import("../components/Footer/Footer.vue")['default']
export const LazyFooterMobile: typeof import("../components/Footer/FooterMobile.vue")['default']
export const LazyFooterMenu: typeof import("../components/Footer/Menu.vue")['default']
export const LazyFooterSocial: typeof import("../components/Footer/Social.vue")['default']
export const LazyHeaderDesktop: typeof import("../components/Header/HeaderDesktop.vue")['default']
export const LazyHeaderMobile: typeof import("../components/Header/HeaderMobile.vue")['default']
export const LazyHeaderLogo: typeof import("../components/Header/Logo/logo.vue")['default']
export const LazyHeaderMenu: typeof import("../components/Header/Menu/Menu.vue")['default']
export const LazyHeroButtons: typeof import("../components/Hero/Buttons.vue")['default']
export const LazyHero: typeof import("../components/Hero/Hero.vue")['default']
export const LazyHeroSubTitle: typeof import("../components/Hero/SubTitle.vue")['default']
export const LazyHeroTitle: typeof import("../components/Hero/Title.vue")['default']
export const LazyHeroImage: typeof import("../components/Hero/image.vue")['default']
export const LazyIconsAboutIcon: typeof import("../components/Icons/AboutIcon.vue")['default']
export const LazyIconsHeart: typeof import("../components/Icons/Heart.vue")['default']
export const LazyIconsSupportIcon: typeof import("../components/Icons/SupportIcon.vue")['default']
export const LazyIconsTerms: typeof import("../components/Icons/Terms.vue")['default']
export const LazyPagesHeaderTeam: typeof import("../components/Pages/Header/HeaderTeam.vue")['default']
export const LazyPagesHeaderTerms: typeof import("../components/Pages/Header/HeaderTerms.vue")['default']
export const LazyPagesHeader: typeof import("../components/Pages/Header/header.vue")['default']
export const LazyPagesHeaderAbout: typeof import("../components/Pages/Header/headerAbout.vue")['default']
export const LazyPagesAbout: typeof import("../components/Pages/about.vue")['default']
export const LazyPagesContact: typeof import("../components/Pages/contact.vue")['default']
export const LazyPagesTeam: typeof import("../components/Pages/team.vue")['default']
export const LazyPagesTerms: typeof import("../components/Pages/terms.vue")['default']
export const LazyPetDanimApiHeaderReadMore: typeof import("../components/PetDanimApi/Header/ReadMore.vue")['default']
export const LazyPetDanimApiHeaderTitle: typeof import("../components/PetDanimApi/Header/Title.vue")['default']
export const LazyPetDanimApiNews: typeof import("../components/PetDanimApi/News.vue")['default']
export const LazyPetDanimApiPostsAuther: typeof import("../components/PetDanimApi/Posts/Auther.vue")['default']
export const LazyPetDanimApiPostsDate: typeof import("../components/PetDanimApi/Posts/Date.vue")['default']
export const LazyPetDanimApiPostsDescription: typeof import("../components/PetDanimApi/Posts/Description.vue")['default']
export const LazyPetDanimApiPostsImage: typeof import("../components/PetDanimApi/Posts/Image.vue")['default']
export const LazyPetDanimApiPostsReadMore: typeof import("../components/PetDanimApi/Posts/ReadMore.vue")['default']
export const LazyPetDanimApiPostsShareSocial: typeof import("../components/PetDanimApi/Posts/Share/social.vue")['default']
export const LazyPetDanimApiPostsSliderItem: typeof import("../components/PetDanimApi/Posts/SliderItem.vue")['default']
export const LazyPetDanimApiPostsTitle: typeof import("../components/PetDanimApi/Posts/Title.vue")['default']
export const LazyPetDanimApiPostsView: typeof import("../components/PetDanimApi/Posts/View.vue")['default']
export const LazyQuestionsHeader: typeof import("../components/Questions/Header/header.vue")['default']
export const LazyQuestionsQuestion: typeof import("../components/Questions/question.vue")['default']
export const LazyServicesPetMarketTabList: typeof import("../components/Services/PetMarket/TabList.vue")['default']
export const LazyServicesPetMarketLanding: typeof import("../components/Services/PetMarket/landing.vue")['default']
export const LazyServicesPetMarketQuestionFaqs: typeof import("../components/Services/PetMarket/question/faqs.vue")['default']
export const LazyServices: typeof import("../components/Services/Services.vue")['default']
export const LazySlider: typeof import("../components/Slider/slider.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyVitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const LazyNuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const LazyPwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const LazyPwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const LazyPwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const LazyPwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const LazyPwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const LazySplide: typeof import("@splidejs/vue-splide")['Splide']
export const LazySplideSlide: typeof import("@splidejs/vue-splide")['SplideSlide']
export const LazySplideTrack: typeof import("@splidejs/vue-splide")['SplideTrack']
export const LazyLCircle: typeof import("@vue-leaflet/vue-leaflet")['LCircle']
export const LazyLCircleMarker: typeof import("@vue-leaflet/vue-leaflet")['LCircleMarker']
export const LazyLControl: typeof import("@vue-leaflet/vue-leaflet")['LControl']
export const LazyLControlAttribution: typeof import("@vue-leaflet/vue-leaflet")['LControlAttribution']
export const LazyLControlLayers: typeof import("@vue-leaflet/vue-leaflet")['LControlLayers']
export const LazyLControlScale: typeof import("@vue-leaflet/vue-leaflet")['LControlScale']
export const LazyLControlZoom: typeof import("@vue-leaflet/vue-leaflet")['LControlZoom']
export const LazyLFeatureGroup: typeof import("@vue-leaflet/vue-leaflet")['LFeatureGroup']
export const LazyLGeoJson: typeof import("@vue-leaflet/vue-leaflet")['LGeoJson']
export const LazyLIcon: typeof import("@vue-leaflet/vue-leaflet")['LIcon']
export const LazyLImageOverlay: typeof import("@vue-leaflet/vue-leaflet")['LImageOverlay']
export const LazyLLayerGroup: typeof import("@vue-leaflet/vue-leaflet")['LLayerGroup']
export const LazyLMap: typeof import("@vue-leaflet/vue-leaflet")['LMap']
export const LazyLMarker: typeof import("@vue-leaflet/vue-leaflet")['LMarker']
export const LazyLPolygon: typeof import("@vue-leaflet/vue-leaflet")['LPolygon']
export const LazyLPolyline: typeof import("@vue-leaflet/vue-leaflet")['LPolyline']
export const LazyLPopup: typeof import("@vue-leaflet/vue-leaflet")['LPopup']
export const LazyLRectangle: typeof import("@vue-leaflet/vue-leaflet")['LRectangle']
export const LazyLTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LTileLayer']
export const LazyLTooltip: typeof import("@vue-leaflet/vue-leaflet")['LTooltip']
export const LazyLWmsTileLayer: typeof import("@vue-leaflet/vue-leaflet")['LWmsTileLayer']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']

export const componentNames: string[]
